/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gabrielaraujo_angular_Main */

#ifndef _Included_com_gabrielaraujo_angular_Main
#define _Included_com_gabrielaraujo_angular_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gabrielaraujo_angular_Main
 * Method:    replaceVariableOcurrencies
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gabrielaraujo_angular_Main_replaceVariableOcurrencies
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
