/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gabrielaraujo_angular_controller_NgControllerBootstrap */

#ifndef _Included_com_gabrielaraujo_angular_controller_NgControllerBootstrap
#define _Included_com_gabrielaraujo_angular_controller_NgControllerBootstrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gabrielaraujo_angular_controller_NgControllerBootstrap
 * Method:    replaceVariableOcurrencies
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gabrielaraujo_angular_controller_NgControllerBootstrap_replaceVariableOcurrencies
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
